name: Test TexLive
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: texinfo mingw-w64-x86_64-texlive-lang-arabic texinfo-tex
      - name: CI-Build
        run: |
          curl -OL https://github.com/msys2/MSYS2-packages/files/6932259/test.zip
          7z x test.zip
      - name: Run
        shell: msys2 {0}
        run: |
          which texi2dvi
          TEX=tex texi2dvi test.texi
         
      - name: run test
        shell: msys2 {0}
        run: |
          cd /
          perl.exe /mingw64/share/texmf-dist/scripts/texlive/fmtutil.pl  --sys --all --cnffile mingw64/etc/texmf/web2c/fmtutil.cnf

          
